// examples/nextjs/src/components/WalletCards/MetaMaskCard.tsx
import { useEffect, useState } from 'react';

import { metaMask } from '../../wallets';
import { Card } from '../Card';

const { hooks, connector } = metaMask;
const {
  useChainId,
  useAccounts,
  useIsActivating,
  useIsActive,
  useProvider,
  useENSNames,
} = hooks;

export const MetaMaskCard = () => {
  const chainId = useChainId();
  const accounts = useAccounts();
  const isActivating = useIsActivating();

  const isActive = useIsActive();

  const provider = useProvider();
  const ENSNames = useENSNames(provider);

  const [error, setError] = useState(undefined);

  // attempt to connect eagerly on mount
  useEffect(() => {
    void connector.connectEagerly().catch(() => {
      console.debug('Failed to connect eagerly to metamask');
    });
  }, []);

  return (
    <Card
      name="MetaMask"
      connector={connector}
      chainId={chainId}
      isActivating={isActivating}
      isActive={isActive}
      error={error}
      setError={setError}
      accounts={accounts}
      provider={provider}
      ENSNames={ENSNames}
    />
  );
};

// examples/vuejs/src/components/WalletCards/MetaMaskCard.vue
<template>
  <div class="wallet-metamask">
    <WalletCard
      :account="account"
      :chain-id="chainId"
      :is-active="isActive"
      :is-activating="isActivating"
    />
    <div style="margin-top: 10px">
      <button @click="connect">connect</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineComponent } from 'vue';

import { metaMask } from '../../wallets';
import WalletCard from './WalletCard.vue';

const {
  connector,
  hooks: { useChainId, useAccount, useIsActive, useIsActivating },
} = metaMask;

const chainId = useChainId();
const account = useAccount();
const isActive = useIsActive();
const isActivating = useIsActivating();

const connect = () => {
  connector.activate(1);
};

defineComponent({
  name: 'MetaMask',
  components: {
    WalletCard,
  },
});
</script>

<style scoped></style>
